Test
Altu-Bitu/Altu-Bitu_hyeonjeong pull request #1
Opened 2021-09-09 05:22 UTC by hyeonjeongs

정렬 과제 제출합니다!! 다들 고생하십니다!ㅜ! 너무 도움 받고 있어요!!

2021-09-09 06:01 UTC, Yuna9949 approved these changes

2021-09-09 06:01 UTC, Yuna9949 commented on 9월 3일 - 정렬/10994.cpp
> +}
간단한 코드여도 주석을 달아주시는 편이 더 좋을 꺼 같아요 :)

2021-09-09 06:07 UTC, Yuna9949 requested changes

2021-09-09 06:07 UTC, Yuna9949 commented on 9월 3일 - 정렬/10994.cpp
> +}
출력할 형태를 백터에 저장하는 함수를 따로 만들어서 main에서 빼는 것이 더 좋을 것같아요.
그리고 출력 형태를 생각해보시면 패턴에 같은 모양이 반복되고 있어요 재귀함수를 사용해보는 건 어떨 까요?

2021-09-09 07:03 UTC, Yuna9949 requested changes
p2. 과제 열심히 너무 잘해주셨어요!! 
세부 리뷰에 말씀드린 것처럼 10994번, 1316번만 수정해서 알려주세요.
다시 리뷰 해드리도록 하겠습니다.
고생 많으셨습니다!!

2021-09-09 07:03 UTC, Yuna9949 commented on 9월 3일 - 정렬/10994.cpp
> +	}
지금도 너무 잘 짜주셨어요. 그런데 별을 채우는 부분을 두 부분으로 나눠서 채우지 않고 하나로 합칠 수 있는 방법이 있을 것 같아요!

2021-09-09 14:09 UTC, hyeonjeongs commented on 9월 3일 - 정렬/10994.cpp
> +}
수정했습니다!!

2021-09-10 07:52 UTC, Yuna9949 reviewed
너무 잘 수정해주셨어요! 
머지해주셔도 될 것 같습니다.
수고 많으셨습니다!!!

2021-09-10 07:52 UTC, Yuna9949 commented on 9월 3일 - 정렬/10994.cpp
> +}
아주 좋아요!!!

2021-09-10 07:52 UTC, Yuna9949 commented on 9월 3일 - 정렬/1316.cpp
> +}
너무 잘 풀으셨어요:)

2021-09-10 08:03 UTC, merged